# Generated by Django 5.0.7 on 2024-09-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
