# Generated by Django 5.0.7 on 2024-09-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_entrega_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
