# Generated by Django 5.0.7 on 2024-09-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_devolucion_entrega_remove_venta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='api.worker'),
        ),
    ]
