# Generated by Django 5.0.7 on 2024-09-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_venta_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='trabajador',
        ),
    ]
