# Generated by Django 5.0.7 on 2024-10-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_venta_trabajador'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ueb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subsidiary')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('efectivo', models.IntegerField(default=0)),
                ('p_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrega_efectivo', to='api.worker')),
                ('p_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe_efectivo', to='api.worker')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='CantidadVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('efectivo', models.IntegerField(default=0)),
                ('entrega_efectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entregaefectivo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unidad')),
            ],
        ),
    ]
